team-diverse/dife-backend

spring-rest-member/src/main/java/com/dife/member/model/Member.java
수정사항 (ERD 반영)
- Boolean 한국인 여부
- 소개 변수값 변경 -> bio
- 공개,비공개 여부 변수값 변경 -> is_public
- 생성일시, 마지막 로그인 기록 변수 설정
보류 사항
- MBTI는 우선 enum 타입 카테고리화
=> refactor: 3/18 회의 반영 Member엔티티 세팅

spring-rest-member/build.gradle, spring-rest-member/src/main/java/com/dife/member/config/MapperConfig.java, spring-rest-member/src/main/java/com/dife/member/config/PasswordEncoderConfig.java, spring-rest-member/src/main/java/com/dife/member/config/SecurityConfig.java, spring-rest-member/src/main/java/com/dife/member/controller/MemberController.java, spring-rest-member/src/main/java/com/dife/member/model/RegisterRequestDto.java, spring-rest-member/src/main/java/com/dife/member/repository/MemberRepository.java, spring-rest-member/src/main/java/com/dife/member/service/MemberService.java
- 유저의 회원가입이 가능하게끔 하자
- Commit message 별로 참고 부탁드립니다!
- JWT 구현 코드가 상당해서 이렇게 작은 단위로 구현을 하고 어플리케이션이 정상 작동하는 기준에서 조금씩 업그레이드 해나가겠습니다.
=> feat(register): 유저 간단 회원가입 구현

spring-rest-member/src/main/java/com/dife/member/config/SecurityConfig.java, spring-rest-member/src/main/java/com/dife/member/controller/MemberController.java, spring-rest-member/src/main/java/com/dife/member/model/dto/MemberUpdateDto.java, spring-rest-member/src/main/java/com/dife/member/service/MemberService.java
- updateService 수정
- 업데이트 dto 입력값 수정 (당장 사용가능, 유의미한 정보들)
- 마이페이지 GET 요청 (회원 정보 조회)
</br>
</br>
- 마이페이지 PUT요청 (회원 정보 수정)
=> refactor: 마이페이지 조회 및 수정 기능 코드 개선

spring-rest-member/build.gradle, spring-rest-member/src/main/java/com/dife/member/config/SecurityConfig.java, spring-rest-member/src/main/java/com/dife/member/controller/MemberController.java, spring-rest-member/src/main/java/com/dife/member/jwt/JWTFilter.java, spring-rest-member/src/main/java/com/dife/member/jwt/JWTUtil.java, spring-rest-member/src/main/java/com/dife/member/jwt/LoginFilter.java, spring-rest-member/src/main/java/com/dife/member/model/Member.java, spring-rest-member/src/main/java/com/dife/member/model/RegisterRequestDto.java, spring-rest-member/src/main/java/com/dife/member/model/dto/CustomUserDetails.java, spring-rest-member/src/main/java/com/dife/member/model/dto/LoginDto.java, spring-rest-member/src/main/java/com/dife/member/service/CustomUserDetailsService.java, spring-rest-member/src/main/java/com/dife/member/service/MemberService.java, spring-rest-member/src/main/resources/application.yml
- jwt 0.12.3 버전 사용
- UserDetail, UsernamePasswordAuthenticationFilter, UserDetailsService 커스텀화
---
1. Clinet 로그인 요청
- 유저가 로그인 입력값으로 넣은 email, password 가져와 token을 구성함
- (해당 token은 시큐리티, 자세하게는 AuthenticationManager가 검증할 token임)
- 해당 필터링 기능은 원래는 시큐리티가 제공하는 UsernamePasswordAuthenticationFilter가 함
**BUT 커스텀화함**
- 우리는 username이 아닌 email로 로그인을 해야 하며 로그인 성공 후에 요청 헤더를 재구성해야 하기 때문임
</br>
2. 필터링된 email, password는 AuthenticationManager에 의해 DB에서 회원 존재 여부를 검사함
- 스프링 시큐리티에서는 UserDetailService가 이를 담당함
**BUT 커스텀화함**
- 우리는 email로 회원을 불러오기 때문 
- UserDetails 타입으로 return (customUserDetails함)
- UserDetails도 email을 갖고 오도록 커스텀화함
</br>
3. JWT 암호화
- 양방향 대침키 방식 사용 : HS256
- 암호화 키는 yml 파일에 저장함 (32비트)
JWTUtil
- email, role, 생성일, 만료일이 저장됨
- 생성자, email확인, 만료일 확인 메서드가 저장됨
</br>
4. JWTUtil 주입
- LoginFilter에 주입
로그인 성공시 토큰 …
=> feat: JWT로그인 초기 구현

spring-rest-file/build.gradle, spring-rest-file/src/main/java/com/dife/file/config/AWSConfig.java, spring-rest-file/src/main/java/com/dife/file/service/FileService.java, spring-rest-file/src/main/resources/application-local.yml
- 기존 로컬로 올라가는 파일을 S3로 올리도록 로직 변경 및 구현
- 커밋 별로 확인부탁드려요!
=> feat(file): POST:api/files 요청 시 S3로 파일 업로드 구현

.github/workflows/tests.yml, rest-api/build.gradle, rest-api/src/test/java/com/dife/api/DifeApplicationTests.java, rest-api/src/test/resources/application.yml
=> ci(test): JUnit Test를 PR 생성 시에 작동하도록 추가한다.

rest-api/src/main/java/com/dife/api/controller/MemberController.java, rest-api/src/main/java/com/dife/api/model/dto/MemberUpdateDto.java, rest-api/src/main/java/com/dife/api/service/MemberService.java
- 프로필 업데이트 기능의 코드를 리팩토링하자.
- 수정 사항과 수정 이유 등의 설명 내용은 각 커밋별로 확인 부탁드립니다!
- 수정에 대해 미흡한게 있으면 자유롭게 공유해주세요!
=> refactor(profile): 프로필 업데이트 코드 리팩토링

.github/workflows/deploys.yml
- environment를 정의해주지 않아서 생기는 Fail 문제 해결
=> fix(ci): github action environment 설정

.github/workflows/deploys.yml
개요
- SSH 전용 포트 secret으로 추가 및 action 버전을 명시한다.
=> fix(ci): SSH 포트 추가 및 버전 명시

.github/workflows/deploys.yml
개요
- ECR 로그인을 하여 접근을 우선 얻어내야 docker pull이 가능하다. 따라서 해당 부분을 추가해준다.
=> fix(ci): ECR 로그인 구현 부분 추가

.github/workflows/deploys.yml
=> chore(ci): 테스트 용도로 환경 변수 프린트 추출

.github/workflows/deploys.yml
수정 사항
- 도커 명령어에서 알고보니, env가 image 명령어 보다 선행해야 인식이 된다는 것을 알게됨 따라서 수정
=> fix(ci): Docker image 명령어 순서 변경

.github/workflows/tests.yml, rest-api/build.gradle, rest-api/src/main/java/com/dife/api/GlobalExceptionHandler.java, rest-api/src/main/java/com/dife/api/controller/ConnectController.java, rest-api/src/main/java/com/dife/api/exception/ConnectDuplicateException.java, rest-api/src/main/java/com/dife/api/exception/IdenticalConnectException.java, rest-api/src/main/java/com/dife/api/model/Connect.java, rest-api/src/main/java/com/dife/api/model/Member.java, rest-api/src/main/java/com/dife/api/model/dto/ConnectRequestDto.java, rest-api/src/main/java/com/dife/api/model/dto/ConnectResponseDto.java, rest-api/src/main/java/com/dife/api/repository/ConnectRepository.java, rest-api/src/main/java/com/dife/api/service/ConnectService.java
개요
- 기존 POST: /api/connects의 세부 구현을 수정하고 일부 로직을 수정하자
- 커넥트 중복등 예외처리 적용, 커넥트에 더 알맞은 모델 속성 수정 등
수정 사항
- 자세한 내용은 커밋별로 읽어주시길 바랍니다!
=> feat(connect): POST: /api/connects/ 세부 구현 및 일부 로직 수정

src/main/java/com/dife/api/jwt/JWTUtil.java, src/test/java/com/dife/api/jwt/JWTUtilTest.java
- JWT Util에 대해 테스트를 작성하자
- 커밋별 메시지 확인 부탁드려요!
- Mock과 JUnit테스트에 관련하여 느낌 잡기로 아래 블로그 참고하시면 좋습니다!
- https://velog.io/@yyong3519/Mockito
- 참고로 이후 PR들에서 여러 테스트 구현으로 테스트 커버리지를 높일 예정입니다 :)
- 테스트 이름 규칙이 굉장히 많은데요, 아래와 같이 정하면 어떨까 싶습니다 :) 
- `method이름_Should결과_When상황`
=> test(jwt): JWTUtilTest 작성

src/main/java/com/dife/api/config/SwaggerConfig.java, src/main/java/com/dife/api/controller/ConnectController.java, src/main/java/com/dife/api/model/Connect.java, src/main/java/com/dife/api/model/dto/ConnectResponseDto.java
- 커넥트 서비스 부분 Swagger 명세서 작성완료했습니다!
- 커넥트 요청 Content-Type은 기본 Swagger 세팅인 form방식이 아닌 json 형태인 존재하여 이를 consumes로 반영해두었습니다!
기존 PR의 테스트 방법을 참고하시면 됩니다!
2개의 회원가입으로 회원 2명 생성 후 한 명의 계정으로 로그인 후 진행
#87 
#88 
#89 
#90 
#91
=> Docs/swagger connect : 커넥트 Swagger 세팅

docker-compose.yml, src/main/java/com/dife/api/config/RedisConfig.java, src/main/java/com/dife/api/redis/RedisPublisher.java, src/main/java/com/dife/api/redis/RedisSubscriber.java, src/main/resources/application.yml
- 채팅에서 사용할 redis의 연결 및 기본 기능을 구현하자
- Commit 별로 확인부탁드려요!
=> chore(redis): Redis 초기 세팅

src/main/java/com/dife/api/controller/BoardController.java, src/main/java/com/dife/api/controller/ChatController.java, src/main/java/com/dife/api/controller/ConnectController.java, src/main/java/com/dife/api/controller/FileController.java, src/main/java/com/dife/api/controller/MemberController.java
- 문제상황 : 프론트 단에서 @RequestParam과 @PathVariable 의 값을 감지 못하는 문제 발생
- 원인 : 
- Spring MVC가 URL 경로 변수의 이름을 자동으로 인식하지 못해 발생하는 오류, 
- 스프링 부트 3.2 이후 버전에서는 파라미터 이름을 자동으로 추론하지 않도록 변경되었다고 함
- 해결 : 
- 명시적으로 name으로 파라미터 값을 지정해줘야 프론트 단에서 감지할 수 있음을 확인
- 모든 Controller에 name을 이용해 파라미터 값을 지정해주었습니다!
@seungholee-dev 
앞선 PR보다 먼저 merge되어야 할 것 같은데 검토해보시고 괜찮으시다면 먼저 merge 진행해도 괜찮을까요??
=> test(fix): 프론트 @RequestParam 닉네임 감지 못함 문제

src/main/java/com/dife/api/controller/ChatroomController.java, src/test/java/com/dife/api/controller/ChatroomControllerTest.java
- 앞서 작성해놓은 회원 Junit 테스트 코드를 참고하여 채팅방 생성 테스트 코드를 작성한 PR입니다!
- 때문에 로직은 거의 동일합니다!
- 클래스 내부의 로직을 반영한 ChatController -> ChatroomController 클래스명 수정
=> Test/chatroom controller : 채팅방 생성 JUnit, Mockito 테스트 작성

.github/workflows/deploys.yml
수정 사항
- AWS에 올라온 Redis (ElasticCache)를 활용하기 위해 env를 설정해준다.
=> ci(redis): Redis 관련 env를 설정

src/main/java/com/dife/api/model/ChatroomSetting.java, src/main/java/com/dife/api/service/ChatService.java
- #116 피드백 반영 PR입니다!
> ChatroomService.java의 isFull함수에서 nCount >= maxCount를 해주는데요, 현재 기본값이 둘 다 0이어서, 따로 값을 넣어주지 않으면 다 찬 것으로 판단되어 true를 리턴하게되어 현재 방에 꽉차서 못들어가는 상황이네요
> 추가로, password에 대한 처리가 이루어지지 않아, 지금 현재 DB에 null 값이 들어가는데요, isWrongPassword 함수에서 getPassword를 했을 때, null 값을 가져와서 equals로 비교해서 에러가 추가로 나네요!
- maxCount, password 피드백 반영했습니다!
수정 PR들 확인 후에 순서대로 merge 진행하겠습니다!
=> refactor/chat-1: 비밀번호, maxCount 피드백 반영

src/main/java/com/dife/api/GlobalExceptionHandler.java, src/main/java/com/dife/api/config/SwaggerConfig.java, src/main/java/com/dife/api/exception/MemberNullException.java, src/main/java/com/dife/api/jwt/JWTFilter.java, src/main/java/com/dife/api/jwt/JWTUtil.java, src/main/java/com/dife/api/jwt/LoginFilter.java, src/main/java/com/dife/api/model/dto/LoginSuccessDto.java, src/main/java/com/dife/api/model/dto/RefreshLoginSuccessDto.java, src/test/java/com/dife/api/jwt/JWTUtilTest.java
- RefreshToken 발급
- 곧 다시 작성하겠습니다..!
=> Refactor/jwt refreshtoken : Refresh 토큰 도입

src/test/java/com/dife/api/controller/MemberControllerTest.java
- MemberController에 대한 Unit test를 작성하자
세부 커밋 PR로 확인부탁드립니다 :)
=> test(member): MemberController Test 초기 작성 및 회원가입 테스트 작성

build.gradle, src/main/java/com/dife/api/config/RedissonConfig.java, src/main/java/com/dife/api/controller/BookmarkController.java, src/main/java/com/dife/api/controller/ChatController.java, src/main/java/com/dife/api/controller/SocketController.java, src/main/java/com/dife/api/controller/SwaggerChatController.java, src/main/java/com/dife/api/model/Chatroom.java, src/main/java/com/dife/api/model/ChatroomSetting.java, src/main/java/com/dife/api/model/Member.java, src/main/java/com/dife/api/model/dto/ChatGetRequestDto.java, src/main/java/com/dife/api/model/dto/ChatRequestDto.java, src/main/java/com/dife/api/model/dto/ChatResponseDto.java, src/main/java/com/dife/api/model/dto/ChatsGetByChatroomRequestDto.java, src/main/java/com/dife/api/service/ChatService.java, src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/RedisLockChatServiceFacade.java
- Redisson을 이용해 락을 걸어 Count에서 발생하던 raceCondition 해결하였습니다..?(?)
- 테스트 코드를 작성하지 않아서 확실하지는 않습니다..!ㅠㅠ
- 이전 PR인 #129 의 일부 피드백은 이어서 수정하겠습니다!
- 만약 해당 방법이 raceCondition을 해결하는 방법이라면 채팅을 DB에 저장할 때도 적용해볼 계획입니다!
- 추가로 엔티티들의 초기값을 정해주면 어떨까 싶어서요..! (null 방지) 어떠신가요?!
- 수정사항 있으시면 바로 반영해 놓겠습니다! :)
=> Fix feat/chat race condition : 채팅방 raceCondition Redisson이용해 해결

src/main/java/com/dife/api/jwt/JWTFilter.java
- Connect 서비스 Controller 형식 통일 중에 PATCH 관련 에러가 발생했는데 시간나실 때 확인해보니 JWTFILTER에서 제대로 return을 하지 않아서 생긴 문제임을 확인했습니다! 
- 추가적으로 JWT 코드 다듬기를 진행했습니다!
=> fix: JWT 코드 오류 발견 및 해결

src/main/java/com/dife/api/controller/LikeController.java, src/main/java/com/dife/api/exception/CommentNotFoundException.java, src/main/java/com/dife/api/model/Comment.java, src/main/java/com/dife/api/model/LikeComment.java, src/main/java/com/dife/api/model/dto/CommentResponseDto.java, src/main/java/com/dife/api/repository/LikeCommentRepository.java, src/main/java/com/dife/api/service/CommentService.java, src/main/java/com/dife/api/service/LikeService.java
- #145 와 로직은 동일
- 댓글과 좋아요는 일대다 관계
- 한 댓글에 한해 한 회원은 한 좋아요만 가능
- Response 는 게시글 좋아요와 동일
=> Feat/like comment : 댓글 좋아요 구현

src/main/java/com/dife/api/config/SwaggerConfig.java, src/main/java/com/dife/api/controller/ChatroomController.java, src/main/java/com/dife/api/controller/LikeController.java, src/main/java/com/dife/api/controller/MemberController.java, src/main/java/com/dife/api/controller/SwaggerChatroomController.java, src/main/java/com/dife/api/controller/SwaggerMemberController.java, src/main/java/com/dife/api/exception/MemberNotAddVerificationException.java, src/main/java/com/dife/api/repository/ChatroomRepository.java, src/main/java/com/dife/api/repository/MemberRepository.java, src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/MemberService.java, src/main/resources/application.yml
- #150 에서 진행했던 고도화 작업에 Swagger를 적용시켰을 때 나타난 오류들을 수정한 PR입니다!
- null 익셉션 방지 처리 및 Swagger 설정 변경 내용이 들어감
- 추가사항은 키워드 검색 기능으로 회원의 검색 기능도 회원의 이름, 닉네임, 한줄 소개에 해당 로직이 들어갈 예정 -> 반영 완료
**DB 업데이트 후** 
- 회원가입1 -> 로그인 -> update
- 회원가입1 -> 로그인 -> 채팅방 생성1 -> update
- 회원 필터링 엔드포인트 실행
- 회원 검색 엔드포인트 실행
- 채팅방 필터링 엔드포인트 실행
- 채팅방 검색 엔드포인트 실행
=> Fix/consume data : consume 로직 오류 사항 수정 및 고도화

src/main/java/com/dife/api/controller/MemberController.java, src/main/java/com/dife/api/model/Chatroom.java, src/main/java/com/dife/api/model/Hobby.java, src/main/java/com/dife/api/model/dto/ChatroomResponseDto.java, src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/MemberService.java
- 프론트에서 필요한 presignurl 추가 및 채팅방 스택오버플로우 해결
=> Fix/presignurl location : 프론트에서 필요한 presignurl 추가

src/main/java/com/dife/api/model/Chat.java, src/main/java/com/dife/api/model/Member.java, src/main/java/com/dife/api/service/ChatService.java, src/main/java/com/dife/api/service/MemberService.java
- 채팅 FE에서 구현하는 과정에서 멤버 정보등 필요한 상황이 발생하여 백엔드 수정
- 리팩토링도 같이 진행
- 커밋별로 확인부탁드려요!
=> refactor(chat): getMemberById 함수 추출 및 ChatService 코드 리팩토링

src/main/java/com/dife/api/config/RedisConfig.java, src/main/java/com/dife/api/model/dto/ChatRedisDto.java, src/main/java/com/dife/api/redis/RedisPublisher.java, src/main/java/com/dife/api/redis/RedisSubscriber.java, src/main/java/com/dife/api/service/ChatService.java, src/test/java/com/dife/api/LocalRedisIT.java
- FE에서 BE로부터 필요한 정보: 채팅 ID, 채팅이 해당한 채팅방 정보, 채팅이 해당한 멤버 정보 등이 필요하게 되어 데이터 전달 형식을 바꾸었음. 그와 동시에 이에 따라 필요한 리팩토링 진행.
- 커밋별로 확인 부탁드려요! :)
=> chore(chat): ChatRedisDto 추가 및 Redis 관련 리팩토링

src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/MemberService.java
- #148 의 피드백 반영한 PR입니다!
- 필터링 코드 피드백 반영
- 로직 변경 : OR -> AND
=> feat/filter-connect-2: (fix) 커넥트에서 사용되는 필터링 기능 구현

src/main/java/com/dife/api/GlobalExceptionHandler.java, src/main/java/com/dife/api/service/MemberService.java, src/test/java/com/dife/api/controller/MemberControllerTest.java, src/test/java/com/dife/api/jwt/JWTUtilTest.java
- JWT 로그인 테스트 코드
- 헤더에 토큰 넣는 테스트 코드 작성 후 작성 예정
=> test/member-login: 로그인 테스트 코드 작성

src/main/java/com/dife/api/service/PostService.java
- 현재 코드에서 postFile이 빈경우는 확인하지만, null인 경우는 처리하지 않고 있다. 이를 구현한다.
=> fix(post): 파일 없이 게시글을 생성할 수 있도록 postFile null처리

src/main/java/com/dife/api/model/Notification.java, src/main/java/com/dife/api/model/NotificationType.java, src/main/java/com/dife/api/model/dto/NotificationResponseDto.java, src/main/java/com/dife/api/service/ChatService.java, src/main/java/com/dife/api/service/CommentService.java, src/main/java/com/dife/api/service/ConnectService.java, src/main/java/com/dife/api/service/LikeService.java, src/main/java/com/dife/api/service/NotificationService.java
- 응답 수정 : TokenResponse -> notification Response
- type으로 불러올 엔티티 타입 명시
- typeId로 엔티티 Id 명시
---
예시
```
- 3번 유저가 1번 댓글에 좋아요를 달았을 경우
- 5번 유저가 4번 (작성자는 3번 유저) 게시글에 좋아요를 눌렀을 경우
```
```
응답 예시
type : POST
typeId : 5
```
요약
```
게시글, 댓글, 좋아요 -> type : POST
채팅 -> type : CHATROOM
id -> POST의 id / CHATROOM의 id
```
=> Fix/notification response : 알림 서비스 (응답 DTO 수정)

src/main/java/com/dife/api/controller/CommentController.java, src/main/java/com/dife/api/controller/PostController.java, src/main/java/com/dife/api/controller/SwaggerCommentController.java, src/main/java/com/dife/api/controller/SwaggerPostController.java, src/main/java/com/dife/api/model/Member.java, src/main/java/com/dife/api/service/CommentService.java, src/main/java/com/dife/api/service/PostService.java
- 댓글 조회 엔드포인트 :
- GET: /api/posts/<post_id>/comments
- 댓글 삭제 엔드포인트 :
- DELETE : /api/comments/{id}
=>  fix/post-comments-endpoint-1: 게시글 댓글 조회 엔드포인트 수정 & 댓글 삭제 구현

build.gradle, src/main/java/com/dife/api/controller/ChatController.java, src/main/java/com/dife/api/controller/ChatroomController.java, src/main/java/com/dife/api/controller/FileController.java, src/main/java/com/dife/api/controller/MemberController.java, src/main/java/com/dife/api/controller/SwaggerChatController.java, src/main/java/com/dife/api/controller/SwaggerChatroomController.java, src/main/java/com/dife/api/controller/SwaggerFileController.java, src/main/java/com/dife/api/controller/SwaggerMemberController.java, src/main/java/com/dife/api/model/Chat.java, src/main/java/com/dife/api/model/ChatType.java, src/main/java/com/dife/api/model/CustomMultipartFile.java, src/main/java/com/dife/api/model/File.java, src/main/java/com/dife/api/model/dto/ChatRedisDto.java, src/main/java/com/dife/api/model/dto/ChatRequestDto.java, src/main/java/com/dife/api/model/dto/ChatResponseDto.java, src/main/java/com/dife/api/service/ChatService.java, src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/FileService.java, src/main/java/com/dife/api/service/MemberService.java, src/main/java/com/dife/api/service/PostService.java
- 채팅에서 STOMP를 적용해 이미지 입력을 받고자 구현한 PR입니다!
- 결론적으로는 성공을 했는지를 확인을 잘 못하겠습니다ㅠ!
- Byte -> Multipart로 바꾸는 과정에서 꼬인 것 같습니다ㅠ!
- 참고한 블로그 : https://velog.io/@dirn0568/%EC%8B%A4%EC%8B%9C%EA%B0%84-%EC%B1%84%ED%8C%85-socket-stomp-sockjs
---
```
- 꼬인 부분
- APIC에서 참고한 블로그대로 이미지 코드를 반환하고자 하였는데 너무 길게 출력이 되어서 APIC으로 테스트가 불가했습니다..
```
---
바꾼 코드
```
file_path = "/Users/suyeon/Desktop/aws.png"
with open(file_path, "rb") as image_file:
byte_data = image_file.read()
print(byte_data)
```
=> Refactor/file include url chat byte : 채팅 String으로 이미지 입력을 받자

build.gradle, src/main/java/com/dife/api/controller/ChatController.java, src/main/java/com/dife/api/controller/ChatroomController.java, src/main/java/com/dife/api/controller/FileController.java, src/main/java/com/dife/api/controller/MemberController.java, src/main/java/com/dife/api/controller/SwaggerChatController.java, src/main/java/com/dife/api/controller/SwaggerChatroomController.java, src/main/java/com/dife/api/controller/SwaggerFileController.java, src/main/java/com/dife/api/controller/SwaggerMemberController.java, src/main/java/com/dife/api/model/Chat.java, src/main/java/com/dife/api/model/ChatType.java, src/main/java/com/dife/api/model/CustomMultipartFile.java, src/main/java/com/dife/api/model/File.java, src/main/java/com/dife/api/model/dto/ChatRedisDto.java, src/main/java/com/dife/api/model/dto/ChatRequestDto.java, src/main/java/com/dife/api/model/dto/ChatResponseDto.java, src/main/java/com/dife/api/service/ChatService.java, src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/FileService.java, src/main/java/com/dife/api/service/MemberService.java, src/main/java/com/dife/api/service/PostService.java
* refactor/file-includeUrl-chatByte-1: 파일 upload시 url에 presignURL 적히도록 수정
* refactor/file-includeUrl-chatByte-2:
- 1. 파일 List형태의 imgCode (여러개 이미지 파일)로 전송 시 MultipartFile로 바꿈
- 2. File업로드 진행
- 3. Redis로 파일 List형태의 presign URL 전송
- 실패 : 파일 저장도 안되고 전송도 안됨
* refactor/file-includeUrl-chatByte-3:
- imgCode에 따른 DTO의 수정사항
* refactor/file-includeUrl-chatByte-4:
- else
=> Refactor/file include url chat byte : 채팅 String으로 이미지 입력을 받자 (#203)

build.gradle, src/main/java/com/dife/api/handler/DisconnectHandler.java, src/main/java/com/dife/api/model/Base64MultipartFile.java, src/main/java/com/dife/api/model/dto/ChatRequestDto.java, src/main/java/com/dife/api/service/ChatService.java, src/main/resources/application-local.yml, src/main/resources/import.sql
- 수연님이 구현해주신 PR #203에서 에러나는 부분을 수정하고 동작을
확인한다.
- CustomMulipartFile을 Base64MultipartFile로 이름 변경
- 불필요한 DiskFileItem과 파일 생성 후 저장 방식을 수연님이 만든
Base64MultipartFile로 생성하여 fileService에 전달
- DisconnectHandler의 함수명 조금 더 명시적으로 변경
- 불필요한 모듈 삭제
=>  fix(채팅): 채팅 파일 전송 수정

src/main/java/com/dife/api/controller/PostController.java, src/main/java/com/dife/api/controller/SwaggerPostController.java, src/main/java/com/dife/api/service/PostService.java
=> refactor/board-getall-1: 게시글 모든 타입도 가져올 수 있게 수정

src/main/java/com/dife/api/model/Bookmark.java, src/main/java/com/dife/api/model/Chat.java, src/main/java/com/dife/api/model/Comment.java, src/main/java/com/dife/api/model/Post.java, src/main/java/com/dife/api/model/TranslateTable.java, src/main/java/com/dife/api/service/TranslationService.java
=> fix/translate-get-1: 게시글 가져올 때 \n 이 아닌 각각으로 가져오기

src/main/resources/application-local.yml
- Liquibase 작업을 거친 이후로 init mode가 매번 필요 없어서 never로 변경 제안
=> chore(init): init mode 기본을 never로 변경 (로컬)

src/main/java/com/dife/api/model/dto/ChatroomResponseDto.java, src/main/java/com/dife/api/service/ChatroomService.java
- 채팅방의 chatroom_type 정보가 없어서 추가를 한다.
=> fix(chat): 채팅방의 chatroom_type 정보가 없어서 추가

src/main/java/com/dife/api/model/Chat.java, src/main/java/com/dife/api/service/MemberService.java, src/main/resources/db/changelog/v1.0/v1.0.2.xml
- Migration 부분에서 파일 삭제로 인해 사라진 부분 복구
=> fix(db): DB Migration에서 파일을 삭제로 누락된 컬럼 부위

src/main/java/com/dife/api/service/ChatroomService.java, src/main/java/com/dife/api/service/CommentService.java
- 채팅방 서비스 코드 최적화에서 writer이 아닌 조회자로 채팅 response DTO를 구성했음
=> hotfix/chatroom-getChatError-1: 채팅방 조회시 작성자와 다름 문제 해결

src/main/java/com/dife/api/model/dto/MemberResponseDto.java, src/main/java/com/dife/api/service/MemberService.java
=> hotfix/file-profileImg-1: File presignURL ID로 가져오기 작업 - ProfileImg
