team-diverse/dife-backend

spring-rest-member/src/main/java/com/dife/member/config/SecurityConfig.java
spring-rest-member/src/main/java/com/dife/member/controller/MemberController.java
spring-rest-member/src/main/java/com/dife/member/service/MemberService.java

- 레포지토리를 이용해 이메일로 회원 찾아 로그인함
테스트에 앞서 DB에 정보가 들어있지 않아야 함 
서버가 켜질 때마다 DB는 초기화됨
DB 명령어
- use DB명 (dife_local)
- drop table member;
그 후 서버 재시작 후 포스트맨 실행
register -> login

fix: 기본 로그인 기능 추가

---

.github/workflows/deploys.yml
rest-api/Dockerfile

- 현재 개발을 하면, prod로 merge가 되어야 한다.
- DockerFile로 Docker를 정의한다.
- 각종 빌드 파일을 컨테이너에 복사함
- jar 파일을 실행하도록 구성
- tmp 폴더를 각종 저장소로 사용
- Github action
- prod에 병합될 때만 스크립트 돌아가도록 설정
- AWS credential을 Github Project에 저장된 Secret에서 가져옴
- ECR로 Docker image를 업로드함
- EC2에 SSH로 접근하여 해당 Docker 컨테이너를 Run함
- 현재 Merge가 되어야만 작동을 해서 테스트를 할 수 있기 때문에 테스트는 생략합니다! (병합 후 문제 있을 시 수정 예정)
- Merge 이후 ec2주소:8080에 접근하면 접근이 가능해지며, prod에 merge될때마다 업데이트 될 겁니다!

ci(pipeline): Docker를 활용해서 컨테이너화하고 Pipeline 구성

---

.github/workflows/deploys.yml

- 파이프라인이 prod에서 작동할 때, 에러가 발생한다.
- 파이프라인에서 아마존 REGION 정보가 필요한데, 현재 내부에서 에러가 발생한다. 조사한 결과, https://github.com/aws-actions/configure-aws-credentials/issues/402 에서처럼, 현재 사용 중인 변수명이 내부와 충돌한다. 따라서 이 변수명을 변경하자
- 추가로, 파이프라인 이름 수정

fix(ci): 아마존 Region 인식이 되지 않는 버그 수정

---

rest-api/src/main/java/com/dife/api/DifeApplication.java
rest-api/src/test/java/com/dife/api/DifeApplicationTests.java

- Mono로 합쳐짐에 따라, DifeApplication으로 메인 어플리케이션의 이름을 변경한다.
[참고] 
IntelliJ에서 gradle을 새로고침 해주시고 run configuration을 저번처럼 설정해주시면 됩니다 :)

refactor: DifeApplication 이름 변경

---

.github/workflows/deploys.yml

- AWS_SECRET_KEY의 이름으로 깃헙 시크릿과 동일하게 맞춰준다

fix(ci): Secret 변수명 불일치 문제 해결

---

.github/workflows/deploys.yml

- docker 빌드 시에 멀티 태그를 달을 때는 -t가 하나 더 있어야하는데 빠졌다. 따라서 수정해주자

fix(ci): docker 태그 명렁어 오타 수정

---

.github/workflows/deploys.yml

- 파이프 라인에서, 도커 이미지가 PULL되지 않는 문제가 생겼다. 확인 결과, 추가 env 변수 정보가 action step에서 받지 못하고 있었다
따라서 추가해준다

fix(ci): EC2에서 도커 이미지를 PULL하지 못하는 현상 해결

---

.github/workflows/deploys.yml

- EC2 아마존 계정 설정을 해야지 docker image를 ecr에서 가져올 수 있다.
- 특히, 이후에 aws configure 이 부분 EC2 UserData.sh로 빼서 최초에만 실행하도록 변경예정 (TODO)

fix(ci): EC2 아마존 계정 설정 부재로 인한 docker image 부재

---

.github/workflows/deploys.yml

문제 및 해결
- 현재, 정의했던 리포 변수들이 Shell로 넘어가지 않아, 조사 결과, envs를 통해 명시적으로 넘겨줘야함을 알게됨.

fix(ci): 환경 변수가 SSH된 상태에서의 Shell로 넘어가지 않는 문제 해경

---

.github/workflows/deploys.yml

.aws 폴더 삭제를 실행 시마다 삭제 안하면 새로운 credential set이 이루어지지 않음 따라서 수정한다.

fix(ci): Github action 실행 전에 .aws 폴더를 삭제해서 새로 credential을 정할 수 있도록 한다

---

.github/workflows/deploys.yml
rest-api/src/main/resources/application.yml

- 현재 변수명을 찾지 못하는 에러가 발생하여 통일성을 위해 AWS_SECRET_ACCESS_KEY로 변수명을 변경한다.

fix(ci): AWS_SECRET_KEY에서 AWS_SECRET_ACCESS_KEY로 변수명 변경

---

rest-api/src/main/resources/application.yml

현재 hibernate 관련 에러가 뜨는 데, Table 생성이 되지 않아 그런 것으로
추측한다. 따라서, 이 에러를 해결해보기 위해 Table Creation을 자동으로
임시 전환한다.

fix(ci): ddl-auto: create를 임시로 활성화 하여 에러를 확인 및 해결

---

.github/workflows/deploys.yml
rest-api/src/main/resources/application.yml

현재, Docker에서 DB_URL을 받아오지 못하는 원인으로 literal 타입이 아니라 string으로 받아서 그런 것으로 예상하여 분리하여 값을 집어넣는 것으로
변경한다.

fix(ci): DB_URL을 DB_HOST, DB_PORT, DB_NAME으로 분리

---

rest-api/src/main/java/com/dife/api/controller/ConnectController.java
rest-api/src/main/java/com/dife/api/service/ConnectService.java

- 보냈던 Connect 요청을 본인이 취소하거나, 상대방의 Connect 요청을
거절하고 싶을 때 요청하는 메서드이다.
- DELETE는 REST API 규격을 확인해보니, 해당 리소스가 없어도 200을
리턴하여 멱등성을 유지함
- 추가로, DELETE는 PATCH와 마찬가지로, 삭제된 리소스를 리턴하지 않고
코드만 리턴하는 경우가 더 흔함
- connecerService에서는 해당 커넥트와 연관된 멤버 (보낸 사람 또는 받은
사람인지 확인하는 Util 함수인 `isConnectRelevant`로 체크

feat(connect): DELETE: /api/connects/{id} 구현

---

rest-api/src/main/java/com/dife/api/controller/ConnectController.java
rest-api/src/main/java/com/dife/api/repository/ConnectRepository.java
rest-api/src/main/java/com/dife/api/service/ConnectService.java

- 커넥트 목록을 가져오는 엔드포인트를 구현한다.
- 특히나, 커넥트 목록을 가져온다는 것은, 친구의 목록을 가져오는 것이다. 이를 염두해두고 구현한다.
- Controller
- 현재 유저 `auth`만 가지고 전체 목록 가져올 수 있도록 service로 패스
- Service
- 현재 멤버를 가져오고, `Connect status`가 `ACCEPTED`인 목록만 가져온다. (이후에 다른 status도 필요하다하면 확장 예정)
- 여러 커넥트가 있을 수 있으니 `List`로 받아온다.
- `@Transactional`을 spring 내부에 구현된 annotation으로 `import` 문을 변경
- `readOnly true`를 걸어서 `getConnects`에서 데이터가 변경되지 않도록 방지

feat(connect): GET: /api/connects/ 구현

---

rest-api/src/main/java/com/dife/api/controller/ConnectController.java
rest-api/src/main/java/com/dife/api/service/ConnectService.java

- GET으로 멤버 id를 백엔드로 요청해서 해당 멤버와 나와의 커넥트를 가져오는 엔드포인트를 구현하자
- 프론트에서 활용 방안은, 내가 해당 멤버와 커넥트 되어있는지에 대한 확인으로 사용한다.
- query param으로 member_id를 받아와서 조회한다. 특히나, Transaction read=true를 걸어서 이후의 코드 실수로 잘못된 데이터가 쓰이는 것을
방지한다.

feat(connect): GET: /api/connects?member_id={id} 구현

---

build.gradle
src/main/java/com/dife/api/ExceptionResonse.java
src/main/java/com/dife/api/GlobalExceptionHandler.java
src/main/java/com/dife/api/config/SecurityConfig.java
src/main/java/com/dife/api/config/SwaggerConfig.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/jwt/JWTFilter.java
src/main/java/com/dife/api/jwt/LoginFilter.java
src/main/java/com/dife/api/model/dto/MemberResponseDto.java
src/main/java/com/dife/api/model/dto/RegisterEmailAndPasswordRequestDto.java
src/main/java/com/dife/api/model/dto/RegisterResponseDto.java
src/main/java/com/dife/api/model/dto/VerifyEmailDto.java
src/main/java/com/dife/api/service/MemberService.java
src/main/resources/application.yml

- #93 에서 추가된 branch
- 프론트와의 협업을 위한 자동화 API 명세서 역할을 하는 **Swagge**r 초기 세팅
- 세부사항은 커밋 확인
- 참고사항 : swagger에서는 기본 response code로 200이 자동으로 지정되어 있어서 이를 예시 코드로 막아서 세팅해둘 예정
---
1. swagger ui 접근 
접근 주소: htttp://localhost:8080/swagger-ui/index.html
+ 서버 시작 (difeApplication)
2. 명세서 api-docs 접근
3. API Test
- Try it out -> 입력값 Test 가능
- form에 맞는 입력값 적고 Execute
결과
- 로그인 Test 도 동일
JWT Token Authorized 성공시
추후 진행 사항
- Swagger가 Token을 감지 못하는 오류 (회원가입2 API) issue
- S3 token 만료 issue
해결하기!

Feat/swagger signup : Swagger 세팅

---

src/main/java/com/dife/api/config/SecurityConfig.java

- 현재 서버에서 swagger-ui/index.html을 접속하면 documentation이 뜨지 않는다.
- 분석 결과, Swagger-UI는 내부적으로 OpenAPI 파일을 접근해야하는데, 그것이 서버 내부의 /api/v1/api-docs/swagger-config로 접근을 하지 못하여 로드가 안되는 것이다. 따라서, Security에서 해당 하위 경로 역시 allow 해준다.

fix(docs): Swagger의 Configuration이 로드되지 않는 현상

---

src/main/java/com/dife/api/controller/ChatController.java
src/main/java/com/dife/api/model/Chatroom.java
src/main/java/com/dife/api/model/ChatroomSetting.java
src/main/java/com/dife/api/model/GroupPurpose.java
src/main/java/com/dife/api/model/Language.java
src/main/java/com/dife/api/model/Tag.java
src/main/java/com/dife/api/model/dto/GroupChatroomRequestDto.java
src/main/java/com/dife/api/model/dto/GroupChatroomResponseDto.java
src/main/java/com/dife/api/repository/GroupPurposesRepository.java
src/main/java/com/dife/api/repository/LanguageRepository.java
src/main/java/com/dife/api/repository/TagRepository.java
src/main/java/com/dife/api/service/ChatroomService.java

- #97 에서 생성한 초기 그룹 채팅방의 고도화
- 채팅방 세팅 @OneToMany 연결을 위한 엔티티 변경
- 채팅방 세부사항 관련 Class 생성
- 기존 단계별 회원가입 방법과 로직 동일
- 구체적인 구현 사항은 커밋 확인 부탁드립니다!
STOMP 그룹 채팅방 고도화

Feat/chat group http implementation : 그룹 채팅방 생성 고도화

---

src/main/java/com/dife/api/jwt/JWTFilter.java

- 코드의 가독성을 위해 로직 변경 없이 코드를 refactoring하자
- lombok `@RequiredArgsConstructor` 어노테이션 사용
- 상수 앞으로 빼놓음
- 코드의 일부를 함수로 빼서 doFilterInternal의 가독성 올림
- 로깅 함수 삭제
- 우선은 로직 변경 없이 코드 형식만 바꾸었습니다.

refactor(jwt): JWTFilter를 로직 변경없이 Refactor

---

src/main/java/com/dife/api/config/SwaggerConfig.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/jwt/JWTFilter.java
src/main/java/com/dife/api/jwt/LoginFilter.java
src/main/java/com/dife/api/model/dto/CustomUserDetails.java
src/main/java/com/dife/api/model/dto/LoginSuccessDto.java

- 온보딩 과정을 고려한 로그인 성공시 is_verified, verification_file_id 보여지게 수정한 PR
- log 삭제
- DB 저장되었던 refreshTokenId 삭제
- 재학생 인증 파일 업로드 하지 않은 상태에서 로그인 
- 재학생 인증 파일 업로드 한 상태에서 로그인 
수정사항 없으시면 merge 하겠습니다! :)

Refactor/login onboading : 온보딩 과정을 고려한 로그인 성공 시 보여질 값 추가

---

src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/model/Chat.java
src/main/java/com/dife/api/model/Chatroom.java
src/main/java/com/dife/api/model/ChatroomSetting.java
src/main/java/com/dife/api/repository/ChatRepository.java
src/main/java/com/dife/api/service/ChatService.java
src/main/java/com/dife/api/service/ChatroomService.java
src/test/java/com/dife/api/controller/ChatroomControllerTest.java

- 기존 만들어 둔 채팅 서비스를 이용한 채팅 DB 저장 PR입니다!
- 300자 이내로 작성된 채팅은 저장되도록 구현했습니다!
- 채팅서비스에서 고려해야 하는 제한사항 추가해두었습니다!
- 자세한 사항은 커밋별 확인 부탁드립니다!
```
{
"chatType" : "CHAT",
"chatroom_id" : 1,
"message": "오늘의 날씨는 매우 맑고 화창하여 외출하기에 좋은 날씨입니다. 주말 동안 친구들과 함께 산책을 하거나 가벼운 운동을 즐기기에도 좋겠습니다. 이와 동시에, 최근에 읽은 책 '시간의 흐름 속에서'는 인간의 삶과 시간에 대한 깊은 통찰을 제공하며, 많은 생각을 하게 만드는 책이었습니다. 책에서는 시간을 어떻게 인식하고 활용하는지에 대한 여러 관점을 탐구하고 있어 매우 흥미롭습니다. 우리는 종종 바쁜 일상 속에서 시간의 중요성을 잊곤 하지만, 이 책을 통해 시간을 소중히 여기고 더 의미 있게 사용하는 방법에 대해 다시 생각하게 됩니다.   ",
"sender" : "sooya"
}
```
- Redis 적용 범위 고민

Feat/chat group chat advancement : STOMP Chat DB 저장 도입

---

src/main/java/com/dife/api/config/RedisConfig.java
src/main/java/com/dife/api/config/WebSockConfig.java
src/main/java/com/dife/api/controller/SocketController.java
src/main/java/com/dife/api/redis/RedisPublisher.java
src/main/java/com/dife/api/redis/RedisSubscriber.java
src/main/java/com/dife/api/service/ChatService.java

- 기존 입장 메시지 발행에 Redis를 거침을 추가
- RedisTemplate을 이용해 Publisher와 Subscriber 간의 상호작용 조절
- RedisSubscriber 수정으로 인한 MessageListenerAdapter 를 주석처리했는데 혹시나 나은 코드가 있다면 알려주시면 감사하겠습니다!
- 입장 테스트 확인 및 APIC 웹소켓 엔드포인트 수정 완료했습니다!
- 채팅, 퇴장 메시지 Redis 적용

Feat/chat group enter redis : Redis를 거친 STOMP 입장 메시지 발행

---

src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/service/MemberService.java

- 랜덤 커넥트에서 보여줄 멤버들을 가져오는 엔드포인트를 구현한다.
- `MemberController.java`
- `count`를 함께 Query Parameter로 요청하고 없으면, 1로 default
- 현재 멤버 비교를 위해 `auth.getName`을 넘겨줌
- `MemberService.java`
- 현재 로직은 인원 수가 적을 때를 기준으로 작성된 알고리즘임.
- 유저 수가 많다면, 한꺼번에 findAll 했을 때 부하가 크다. 다만 그 알고리즘을 미리 구현한다면, 지금처럼 인원 수가 적을 때 가져온 인원의
겹치는 횟수가 많아지므로 오히려 마이너스이다. 이후에 유저가 꽤 생기면
성능 테스트와 알고리즘 개선을 해야한다. (유저가 삭제되어 id 값이 없는
경우도 생각해야함)
- 우선 모든 멤버를 가져오고 (본인 제외), 그것을 섞는다. 그 다음에 count 만큼 잘라서 리턴한다.
- 참고로, 요청 인원 수보다 현재 인원이 적은 경우 현재 인원을 기준으로 계산을 합니다. (다들 이렇게 하더라구요!)

feat(member): GET: /random 랜덤으로 멤버를 가져오는 API Endpoint 구현

---

build.gradle
src/main/java/com/dife/api/config/AWSConfig.java
src/main/java/com/dife/api/config/SecurityConfig.java
src/test/java/com/dife/api/config/LocalAWSConfig.java
src/test/resources/application.yml

- S3와 Redis등 현재 테스트에서 에러가 나고 있다. 이는, 테스트 환경에서 S3와 Redis 인스턴스를 받지 못하는 상황에서 발생하는 것이기에 로컬
테스트에서 이들을 만들어주도록 하는 testcontainer를 사용하자

build(test): testcontainer로 S3, Redis 추가

---

src/test/java/com/dife/api/LocalRedisIT.java
src/test/java/com/dife/api/LocalS3IT.java
src/test/java/com/dife/api/config/LocalAWSConfig.java
src/test/java/com/dife/api/config/LocalRedisConfig.java
src/test/java/com/dife/api/config/TestConfig.java

현재 RaceCondition등 여러 테스트에서 @SpringBootTest를 활용해서 context loading이 필요하다.
그런데, 현재 외부 Bean이 테스트에서 적절히 대체되지 않아 에러가 발생한다.
따라서, 임시 방편으로 처리를 해준다.

test(config): @SpringBootTest를 사용하면 에러가 나는 현상 잡기

---

src/main/java/com/dife/api/config/WebConfig.java

- 현재, Websocket을 구현하면서 iOS를 터널링을 하지 않는 이상, iOS 개발이 어렵다. 따라서 현재 Web으로 개발을 하고 있는데, 이를 위해 localhost:8081 CORS를 허용해준다. (브라우저에서 테스트하기 때문에 필요하다)
(이후에 필요에 따라 CORS 엔드포인트 허용 env 변수로 뺄 예정 -> 아직은 Web버전 지원을 하지 않기 때문에 8081로 남겨두고자함)

fix(cors): HTTP Request CORS 문제 해결

---

src/main/java/com/dife/api/model/Chat.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/model/dto/ChatRequestDto.java
src/main/java/com/dife/api/model/dto/ChatResponseDto.java
src/main/java/com/dife/api/redis/RedisPublisher.java
src/main/java/com/dife/api/redis/RedisSubscriber.java
src/main/java/com/dife/api/service/ChatService.java

- 채팅에 회원의 닉네임과 보낸시각 표시하는 PR입니다!
- Chat, ChatRequestDto, ChatService, ChatResponseDto:
- 채팅에 보낸 시간, 보낸이의 별명 추가
- RedisSubscriber:
- 저장되는 채팅에만 created 표시되도록 이때, 채팅이 생성되는 시간을 가져올 경우 직렬화 오류 발생 -> LocalDateTime의 경우 그 차이가 00:00:00.00:00:20 차이이기 떄문에 독립적으로 LocalDateTime 설정
- Member:
- 회원이 가진 채팅방 Set 불러오기 가능하도록

refactor/chat-add-dto: 채팅에서 필요한 정보 추가

---

src/main/java/com/dife/api/controller/LikeController.java
src/main/java/com/dife/api/controller/PostController.java
src/main/java/com/dife/api/controller/SwaggerPostController.java
src/main/java/com/dife/api/exception/DuplicateLikeException.java
src/main/java/com/dife/api/exception/LikeNotFoundException.java
src/main/java/com/dife/api/model/LikePost.java
src/main/java/com/dife/api/model/LikeType.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/model/Post.java
src/main/java/com/dife/api/model/PostLike.java
src/main/java/com/dife/api/model/dto/LikeCreateRequestDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/repository/LikePostRepository.java
src/main/java/com/dife/api/service/LikeService.java
src/main/java/com/dife/api/service/PostService.java

- 게시글에 좋아요를 구현한 PR입니다!
> 게시글 좋아요와 게시글 : 다대일 관계
> 게시글 좋아요와 회원 : 다대일 관계
> 좋아요 누르기는 POST, 좋아요 누르기 취소는 DELETE
> 좋아요 누르기 취소 구현시 양방향 관계로 인한 remove를 모두 진행해줌 
- 게시글 좋아요 엔티티를 생성해 구현하였으며 세부 사항은 커밋별로 확인 부탁드립니다!
- 좋아요의 갯수는 엔티티에 필드로 반영되는 것이 아닌 GET할 때 List의 Size로 DTO에 반영되는 것입니다.
- 같은 로직으로 댓글 좋아요 엔티티를 구현하되 좋아요한 댓글을 불러오는 기능은 넣지 않을 예정입니다.
```
{
"id": 1,
"title": "title1",
"content": "내용",
"boardType": "TIP",
"isPublic": true,
"likesCount": 1,
"viewCount": 0,
...
}
```
200 OK
409 Conflict
401 UnAuthorized
- 댓글 좋아요 구현

Feat/like post : 게시글 좋아요 구현

---

src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/controller/SocketController.java
src/main/java/com/dife/api/controller/SwaggerChatroomController.java
src/main/java/com/dife/api/model/ChatroomSetting.java
src/main/java/com/dife/api/model/GroupPurpose.java
src/main/java/com/dife/api/model/Language.java
src/main/java/com/dife/api/model/Tag.java
src/main/java/com/dife/api/model/dto/ChatroomResponseDto.java
src/main/java/com/dife/api/repository/GroupPurposesRepository.java
src/main/java/com/dife/api/repository/HobbyRepository.java
src/main/java/com/dife/api/repository/LanguageRepository.java
src/main/java/com/dife/api/repository/TagRepository.java
src/main/java/com/dife/api/service/ChatroomService.java
src/main/java/com/dife/api/service/MemberService.java

- 기존의 태그 (회원에 따른 유일한 언어 or 취미) 좋게 개선한 코드와
- 그룹 채팅방에 이미지 업로드를 위한 코드를 반영한 PR입니다!
- 기존의 태그 로직은 변경된 태그들과 기존의 태그들이 겹쳐 수정 사항을 반영하지 못한다는 문제점을 찾아 개선했습니다.
- 프로필 이미지는` GET` 요청 시에만 presign URL이 보이도록 할 예정입니다!
- 자세한 내용은 커밋별 참고 부탁드립니다!
- 언어에` "KOREAN", "ENLGISH"` 입력
- PUT 전송
- `"KOREAN"`만 다시 입력
- PUT 전송
-` "ENLGISH`"만 다시 입력
- PUT 전송
- 수정 요청 파라미터 검토 및 개선

Refactor/tags : 태그 목록 로직 수정 및 채팅방에 프로필 이미지 업로드 추가

---

src/main/java/com/dife/api/redis/RedisSubscriber.java

프론트엔드에서 상대 채팅과 본인 채팅의 구별이 더 쉽도록 하기 위해, 채팅 메시지에 member_id 정보를 추가한다

feat(chat): 뿌려지는 채팅 메시지에 member_id 정보 추가

---

src/main/java/com/dife/api/config/MapperConfig.java
src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/jwt/JWTFilter.java
src/main/java/com/dife/api/model/ChatroomSetting.java
src/main/java/com/dife/api/model/Comment.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/model/Post.java
src/main/java/com/dife/api/model/dto/ChatroomResponseDto.java
src/main/java/com/dife/api/model/dto/CommentResponseDto.java
src/main/java/com/dife/api/model/dto/MemberResponseDto.java
src/main/java/com/dife/api/service/ChatroomService.java
src/main/java/com/dife/api/service/MemberService.java

- Update 메서드를 고도화 시킨 PR입니다!
**변경된 내용**
- required 되어있던 학생증 인증 파일 required 해제
- 불필요한 게시글 관련 viewCount 삭제
- 파일 초기값 null 화 및 엔티티화 (모든 파일에 한해)
- 기존 값과 변화가 없거나 null 값이 들어온다면 update 기능에 맞춰 기존값 유지
- 자세한 내용은 커밋별로 확인 부탁드립니다! :)
**!학생증 인증 부분 변경 로직!**
- 기존의 학생증 인증 파일 초기값을 "empty"로 설정해 인증 처리를 해왔는데
- file 엔티티 사용으로 인해 약간의 변경사항이 있을 것 같습니다..!
**1. 온보딩 완료 회원 / 미완료 회원 구분 -> 
온보딩 완료 회원 : /profile의 ResponseDTO의 username != ""
온보딩 미완료 회원 : /profile의 ResponseDTO의 username == ""**

fix/member-post: 학생증 인증 파일 required 해제

---

src/main/java/com/dife/api/controller/NotificationController.java
src/main/java/com/dife/api/exception/NotificationException.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/model/Notification.java
src/main/java/com/dife/api/model/NotificationType.java
src/main/java/com/dife/api/model/dto/NotificationResponseDto.java
src/main/java/com/dife/api/repository/NotificationRepository.java
src/main/java/com/dife/api/service/NotificationService.java
src/main/java/com/dife/api/service/PostService.java

- SSE를 기반으로 한 알림서비스 초기 세팅 PR입니다! 
- 웹소켓과 유사하게 구독 -> 전송 구조로 되어있습니다.
- 엔티티의 구성 요소는 이전에 slack에서 공지한 바와 같습니다!
- 추가적으로 회원별 알림 List를 확인하는 메서드도 포함되어 있습니다.
- 다른 서버에서 온 알람의 경우 이전에 채팅에서 사용했던 방법처럼 Redis를 이용해 해당 뿌려줄 것인지?!
- 회원가입1 -> 로그인
- SSE 연결 (GET mapping)
- 게시글 생성 
- SSE 확인
- 피드백 반영
- 다른 서비스에도 알림 적용

Feat/notification : 알림 서비스 세팅

---

src/main/java/com/dife/api/service/MemberService.java

- 현재 멤버 프로필 업데이트 함수에서 이미 인증된 유저도 학생증을 필요로 한다. 따라서 이미 인증되어 있는지 확인하는 조건을 추가한다.
- update함수에서 is_verified if 조건이 추가된 이유는 update 함수를 온보딩 단계에서도 활용하고, 마이페이지에서도 프로필을 업데이트 할 때도 사용해서 그렇다. 따라서, 온보딩 단계에서는 기존처럼 정상적으로 학생증을 요구하고 프로필을 업데이트하는 과정에서는 이미 인증이 되어있는 것을 확인하여 학생증을 요구하지 않도록 하는 부분이다.

fix(member): Member Profile 업데이트 함수에 is_verified 조건 추가

---

src/main/java/com/dife/api/controller/FileController.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/controller/PostController.java
src/main/java/com/dife/api/controller/SwaggerFileController.java
src/main/java/com/dife/api/controller/SwaggerMemberController.java
src/main/java/com/dife/api/controller/SwaggerPostController.java
src/main/java/com/dife/api/exception/FileUploadException.java
src/main/java/com/dife/api/model/File.java
src/main/java/com/dife/api/model/FileLocation.java
src/main/java/com/dife/api/model/Post.java
src/main/java/com/dife/api/model/dto/FileDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/repository/PostRepository.java
src/main/java/com/dife/api/service/FileService.java
src/main/java/com/dife/api/service/MemberService.java
src/main/java/com/dife/api/service/PostService.java

- 파일 서비스를 이용해 기존의 파라미터 및 정보 DTO에 포함했어야 할 서비스를 분리해보았습니다.
- 적용한 코드가 서비스 독립적이라고 생각하는데 (기존의 코드는 파라미터로 다 받아야 해서 수고스럽다고 갑자기 생각이 들어서..!ㅎㅎ)
- 테스트 코드 작성완료 후에 팀원분들도 동의하신다면 해당 코드로 파일 서비스를 수정할 계획입니다!
- 본인글 조회 API는 엔드포인트를 찾아보니 /posts/me 혹은 /members/posts 두 가지로 많이들 사용하시는데 제 생각으로는 마이페이지에서 접근하는 API이므로 members에서 이어나가야 하지 않을까 싶었는데 혹시 더 좋은 엔드포인트가 있으시다면 알려주세요!!
- 회원가입 -> 로그인 -> 파일 업로드 (POST 요청)-> 파일의 OriginalName (cookie.jpeg)로 파라미터를 넣음 (GET 요청) -> 이미지 파일의 presignUrl이 나옴
- 회원가입 -> 로그인 -> 게시글 작성 -> 본인 글 조회 엔드포인트 접근 (GET 요청)
- 파일 수정은 파일 삭제와 동일함
- 회원가입 -> 로그인 -> 게시글 조회 (위의 테스트를 수행했다는 가정 하에) -> 파일 삭제 API (DELETE 요청) -> 게시글 조회 / presignURL 조회 (GET 요청)

Refactor/post-file-member : 파일 엔드포인트 분리 사용 및 회원 본인이 작성한 글 조회 API 추가

---

src/main/java/com/dife/api/service/ConnectService.java

- connect에서 accept하는 patch request에서 Connect Not Found Exception이 발생한다.
- connectId를 넘겨줘야하는데, memberId를 넘겨주고 있어서 에러가 나고 있었음
- connectId를 함수의 파라미터로 이름 명시하고, acceptConnect 함수에서 connectRepository에서 해당 커넥트가 없으면 에러를 리턴하므로, 불필요한
조건문을 삭제한다.

fix(connect): 커넥트에서 Accept 안되는 부분 수정

---

src/main/java/com/dife/api/controller/BookmarkController.java
src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/controller/CommentController.java
src/main/java/com/dife/api/controller/ConnectController.java
src/main/java/com/dife/api/controller/LikeController.java
src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/controller/SwaggerBookmarkController.java
src/main/java/com/dife/api/exception/DuplicateBookmarkException.java
src/main/java/com/dife/api/model/Bookmark.java
src/main/java/com/dife/api/model/BookmarkType.java
src/main/java/com/dife/api/model/Comment.java
src/main/java/com/dife/api/model/dto/BookmarkCreateRequestDto.java
src/main/java/com/dife/api/model/dto/BookmarkResponseDto.java
src/main/java/com/dife/api/model/dto/CommentResponseDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/repository/BookmarkRepository.java
src/main/java/com/dife/api/service/BookmarkService.java
src/main/java/com/dife/api/service/CommentService.java

- 댓글/대댓글도 북마크를 누를 수 있게 함
- 북마크 중복 생성을 방지함
- 댓글 조회는 /comments/{postId} 로 함
- 대댓글은 DTO의 parent_id가 null이 아나며 최초 댓글이라면 parent_id가 null임으로 구별함
- 북마크 취소는 좋아요 취소방법과 동일함
- 모든 중복생성 익셉션은 409 conflict로 통일함
- 댓글은 게시글이 아닌 댓글 조회 엔티티에서 확인해야 함
1. 회원가입 -> 로그인 -> 게시글 생성 -> 댓글 생성 -> 대댓글 생성 후 댓글 조회 엔티티에서 확인
2. 회원가입 -> 로그인 -> 게시글 생성 -> 북마크 생성 -> 댓글 생성 -> 북마크 생성 -> 댓글 조회 엔티티에서 확인 (대댓글 북마크 생성도 동일)

Refactor/bookmark postservice : 북마크 서비스에 댓글 추가 및 댓글 서비스 수정

---

src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/controller/SwaggerMemberController.java
src/main/java/com/dife/api/repository/CommentRepository.java
src/main/java/com/dife/api/service/MemberService.java

- 마이페이지 측 API에 조회 API 생성
- /members/comments GET 요청 시 회원이 작성한 댓글 조회 가능 
- 게시글과 동일하게 최신순 정렬 적용
검토 후에 최종본 코드일 때 은영님 Assign 하도록 하겠습니다! :)

feat/member-comment-1: 회원이 작성한 댓글 조회 API 추가

---

src/main/java/com/dife/api/controller/CommentController.java
src/main/java/com/dife/api/controller/PostController.java
src/main/java/com/dife/api/controller/SwaggerCommentController.java
src/main/java/com/dife/api/controller/SwaggerPostController.java
src/main/java/com/dife/api/model/dto/CommentResponseDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/service/CommentService.java
src/main/java/com/dife/api/service/PostService.java

- 기존의 좋아요와 게시글 사이에 있는 LikePost 엔티티를 이용해 좋아요 누름 여부를 판단 후에 responseDto에 
- isLiked 값을 갱신해주는 로직입니다.
- 게시글, 댓글 동일한 로직으로 작동합니다.
- 회원가입, 로그인 후 게시글 생성 -> 게시글 좋아요 POST 요청 (type과 postId or commentId 갱신 주의) -> 게시글 GET 요청
- 하면 응답 DTO에 isLiked값이 true로 바뀌어짐을 확인할 수 있습니다! :)
- 댓글 테스트도 동일한 방법으로 테스트합니다.
```
[
{
"id": 1,
"content": "다른 댓글 내용2",
"isPublic": true,
"parentComment": null,
"likesCount": 1,
"isLiked": true,  
...
```

Feat/dto isliked : 응답 DTO에 좋아요 누름 여부 표시

---

src/main/java/com/dife/api/model/dto/CommentResponseDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/service/CommentService.java
src/main/java/com/dife/api/service/PostService.java

- 프론트에서 필요한 커뮤니티 정보를 응답 DTO에 추가한 PR입니다!
1. 게시글 조회 시 댓글 갯수 표시
2. 댓글 조회 시 종속되어 있는 게시글 정보 포함
- 회원가입, 로그인 후 게시글 생성 -> 댓글 생성 -> 대댓글 생성
응답 예시
> 게시글 조회 시 (/posts/{postId} - GET)
```
{
"id": 3,
"title": "제목3",
"content": "내용",
"boardType": "FREE",
"isPublic": true,
"isLiked": false,
"commentCount": 1,
...
```
> 댓글 생성 시 (/comments - POST, /comments/{postId} - GET)
> 댓글
```
{
"id": 2,
"content": "다른 댓글 내용2",
"isPublic": true,
"isLiked": null,
"post": {
"created": "2024-08-02T04:14:23.187793",
"modified": "2024-08-02T04:14:23.187793",
"id": 4,
...
```
> 대댓글
```
{
"id": 3,
"content": "다른 댓글 내용",
"isPublic": true,
"isLiked": false,
"post": {
"created": "2024-08-02T04:14:23.187793",
"modified": "2024-08-02T04:14:23.187793",
"id": 4,
...
"parentComment": {
"created": "2024-08-02T04:14:38.854485", …
```

Fix/community: 프론트에서 필요한 커뮤니티 정보를 응답 DTO에 추가

---

.github/workflows/deploys.yml
build.gradle
src/main/java/com/dife/api/config/AWSConfig.java
src/main/java/com/dife/api/config/SecurityConfig.java
src/main/java/com/dife/api/jwt/JWTFilter.java
src/main/resources/application-local.yml
src/main/resources/application.yml

- 기존에 EC2만을 사용해서 Pipeline을 구성했는데, ECS로 이전함에 따라,
알맞게 파이프를 구성하자
- 기존에 넘겨주었던 많은 Secret 환경 변수들을 AWS에 안전하게 저장하기
때문에 pipeline에 굳이 환경변수를 노출할 필요가 없어져서 삭제한다.
- Prod에 Push를 날리면, ECS에서 Task Definition을 새로 만들어서 새로운 컨테이너를 돌린다.
- Spring Actuator를 install하여, /health path에서 Health Check가
이루어지도록 한다. 이는, 서버가 다운되었는지 확인하는 Load balancer의
요구 사항이므로 추가한다.
- 추가로, 해당 path를 누구나 접근할 수 있게 열어놓는다.
- 아마존에서 배포 시에는, 아마존의 secretKey, accessKey등의 키가 없어도
S3 접근이 가능하다. 따라서 이 부분을 삭제하고 로컬에서는 테스트할때
필요하므로, 로컬 환경에서만 필요하도록 설정해놓는다.

ci(ecs): AWS ECS를 활용한 개선된 Pipeline 구성 및 설정

---

src/main/java/com/dife/api/controller/NotificationController.java
src/main/java/com/dife/api/controller/SwaggerNotificationController.java
src/main/java/com/dife/api/repository/NotificationTokenRepository.java
src/main/java/com/dife/api/service/NotificationService.java
src/main/resources/import.sql

```
- NotificationController, getNotifications:
- 알림 리스트를 받아올 때 pathVariable에 deviceId 추가해 deviceId별 알림 리스트를 받아올 수 있도록 함
- 이때 deviceId를 가진 회원만이 알림들을 가져올 수 있음
- sendNotificationTokens:
- deviceId 마다 하나의 토큰만이 생성되도록 로직 수정
- isTokenAlive 메서드를 추가해 이전에 해당 device 앞으로 된 토큰이 있는지 확인하고 없다면 새로 만들고
- 기존에 회원이 등록했던 deviceIdfh 된 토큰이라면 새로 만들지 않고 응답 DTO를 작성함
```
1. 같은 유저 각 DeviceId마다 알림 1개 생성 
```
1. 5번 유저로 로그인
2. deviceId6으로 POST :/notifications/push
3. 본인 계정으로 로그인
4. 토큰으로 1번 게시글(작성자 : gusuyeon@gmail.com)에 대해 댓글 생성 (POST :/comments)
5. GET :/notifications/deviceId5 해서 댓글 생성 알림 1개 온 것 확인
6. GET :/notifications/deviceId6 해서 댓글 생성 알림 1개 온 것 확인
```
2. 다른 유저 로그인 시 새로운 DeviceId 쟁취
```
1. 본인 계정으로 로그인 및 게시글 작성(POST)
2. POST :/notifications/push 에서 5번 유저의 deviceId 쟁취 
{
"pushToken" : "pushToken",
"deviceId" : …
```

fix/notificationToken-byDeviceId-1: DeviceId마다 알림 리스트를 GET할 수 있도록

---

src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/controller/SwaggerChatroomController.java
src/main/java/com/dife/api/model/Comment.java
src/main/java/com/dife/api/service/ChatroomService.java
src/main/java/com/dife/api/service/MemberService.java

구현사항
```
- 승호님의 기존 random 메서드 shuffle 화 재활용
- 나머지 로직은 다른 필터링 로직과 동일
- 랜덤한 채팅방 10개의 후보군으로는 그룹 채팅방, 인원수가 꽉 차지 않은 채팅방이 보여짐
```
추가 사항 (탈퇴 시 댓글 삭제 처리)
```
- 솔로 댓글일 경우 -> 탈퇴 시 자동 삭제
- 자식 댓글일 경우 -> 탈퇴 시 자동 삭제
- 부모 댓글일 경우 -> 탈퇴 시 NULL 처리
```

feat/chatroom-random-1: 랜덤하게 10개 그룹 채팅방 뽑아오는 API 추가 및 탈퇴 시 댓글 삭제 처리 로직 수정

---

src/main/java/com/dife/api/GlobalExceptionHandler.java
src/main/java/com/dife/api/exception/file/S3FileNameInvalidException.java
src/main/java/com/dife/api/exception/file/S3FileNotFoundException.java
src/main/java/com/dife/api/model/File.java
src/main/java/com/dife/api/model/dto/FileDto.java
src/main/java/com/dife/api/service/ChatService.java
src/main/java/com/dife/api/service/FileService.java
src/main/java/com/dife/api/service/MemberService.java
src/main/java/com/dife/api/service/PostService.java
src/main/resources/db/changelog/v1.0/v1.0.0.xml

- 현재 DB에 pre-signed url을 저장하고 있는데, pre-signed url은
일시적으로만 사용하는 것이므로 DB에 저장을 하지않도록 한다.
- 프론트엔드 코드에서는 다행히 File 모델의 url 값을 필요로 하는 부분은 없어서
리팩토링 진행 (presignedImgProfile로 이미지 렌더링을 하더라구요)
- 반복되는 코드 genereatePresignedUrl 함수로 리팩토링
- exception의 경우에 global exception handler가 있으므로, try catch 걸지
않아도, 괜찮아서 삭제

refactor(file): File 모델의 URL 컬럼 삭제, Exception 리팩토링

---

src/main/java/com/dife/api/controller/SwaggerReportController.java
src/main/java/com/dife/api/model/Chatroom.java
src/main/java/com/dife/api/model/Report.java
src/main/java/com/dife/api/model/dto/ChatroomResponseDto.java
src/main/java/com/dife/api/model/dto/ReportRequestDto.java
src/main/java/com/dife/api/model/dto/ReportResponseDto.java
src/main/java/com/dife/api/service/ChatroomService.java
src/main/java/com/dife/api/service/ReportService.java
src/main/resources/db/changelog/changelog-master.xml
src/main/resources/db/changelog/v1.0/v1.0.2.xml

- Report에 외래키 chatroom 추가
- 로직은 기존 신고와 댓글/게시글과의 연관관계와 동일
- 단체 채팅방 참여 여부 DTO에 표시 완료
- swagger, liquibase 작성완료

refactor/report-add-chatroom-1: 그룹 채팅방 신고 추가

---

src/main/java/com/dife/api/controller/MemberController.java
src/main/java/com/dife/api/controller/SwaggerMemberController.java
src/main/java/com/dife/api/exception/VerifyCodeNotFoundException.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/model/dto/MemberResponseDto.java
src/main/java/com/dife/api/service/MemberService.java
src/main/resources/db/changelog/v1.0/v1.0.4.xml

- MemberService 메서드 분리 및 비밀번호 변경 후 비밀번호 재설정 가능하도록 로직 추가한 PR입니다!
- NO AUTH 상태에서, 비밀번호 인증번호를 이용한,  비밀번호 변경을 용도의 PATCH 엔드포인트를 추가해두었습니다!
---
(edited) 테스트 시나리오 
비밀번호 까먹었을 때에 재설정
```
- GET :/members/change-password로 변경 메일 발송 (인증번호 받기 용도)
- 인증번호를 받은 후에 사용자는 NO AUTH (로그인 불가 상태이므로) 상태로 비밀번호 변경 인증번호, 변경할 새 비밀번호, 계정 이메일을 입력해 비밀번호를 변경하게 됨
```
Auth 상태에서 비밀번호 재설정
`- 이미 인증받은 사용자이므로 update PUT 요청에서 변경 가능할 수 있게 열어둠`
인증번호 불일치시 403 익셉션

Perf/member module : MemberService 모듈화 및 비밀번호 변경 후 로직 추가

---

src/main/java/com/dife/api/controller/ChatroomController.java
src/main/java/com/dife/api/controller/SwaggerChatroomController.java
src/main/java/com/dife/api/service/ChatroomService.java

- 현재 그룹채팅 전용으로 사용 중인 /chatrooms/getGroupChatrooms와 /chatrooms/getGroupChatroom을 1:1도 사용할 수 있도록 겸용으로 바꾼다.
- 함수명 변경
- 1:1 채팅의 경우에는 방장이 없으므로, null 값이 들어가서 에러가 남. 따라서, GROUP이 있는 경우에만 값처리를 해주자

fix(chat): 그룹 채팅 전용 조회 API를 1:1 겸용으로 개조

---

src/main/java/com/dife/api/model/dto/CommentResponseDto.java
src/main/java/com/dife/api/model/dto/ConnectResponseDto.java
src/main/java/com/dife/api/model/dto/MemberRestrictedResponseDto.java
src/main/java/com/dife/api/model/dto/NotificationTokenResponseDto.java
src/main/java/com/dife/api/model/dto/PostResponseDto.java
src/main/java/com/dife/api/service/BlockService.java
src/main/java/com/dife/api/service/ChatService.java
src/main/java/com/dife/api/service/ChatroomService.java
src/main/java/com/dife/api/service/CommentService.java
src/main/java/com/dife/api/service/ConnectService.java
src/main/java/com/dife/api/service/LikeService.java
src/main/java/com/dife/api/service/NotificationService.java
src/main/java/com/dife/api/service/PostService.java

- 불필요한 회원정보를 제외한 회원 응답 DTO 변경 사항입니다!
- MemberService에는 제외함
```
@Getter
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "표시용 회원정보 응답 데이터 전송 객체")
public class MemberRestrictedResponseDto {
private Long id;
@Schema(description = "닉네임", example = "sooya")
private String username;
@Schema(description = "S3에 저장되는 프로필 이미지", example = "cookie.jpeg")
private File profileImg;
}
```

perf/exceptMemberDto-1: 수정 회원 응답 DTO 적용 (MemberService 제외)

---

build.gradle
src/main/java/com/dife/api/config/SecurityWebSockConfig.java
src/main/java/com/dife/api/config/WebSockConfig.java
src/main/java/com/dife/api/config/WebSocketInterceptor.java
src/main/java/com/dife/api/service/ChatService.java

채팅에 JWT 토큰을 넣어 Authorization을 주입한 PR입니다!
Interceptor을 이용해 Authorization에서 회원 정보를 가져옵니다.
STOMP 전용 시큐리티를 작성해 보안을 추가했습니다. (ws/는 여전히 permitall()입니다)
WebSocket 요청이기 때문에 기존의 FilterChain을 통과하지 않으며 대신
Interceptor에서 그 역할을 대신합니다.
#221  을 보완한 PR입니다. (해당 PR은 닫도록 하겠습니다)
---
> 참고사항
Postman애 해팅 (Auth)로 요청 새로 만들어두었습니다.
테스트 한 사항 : CONNECT > SEND

Feat/chat authorization : 일대일 채팅 JWT Authorization 넣기 

---

src/main/java/com/dife/api/handler/DisconnectHandler.java
src/main/java/com/dife/api/service/ChatService.java

기존에 DISCONNECT했던 방법인 STOMPHEADERACESSOR로 UNSUBSCRIBE를 진행해 구독 취소를 함
- 퇴장해도 세션 종료 안됨 확인
- 퇴장해도 멤버가 속한 다른 채팅방에 영향 안감 확인
- 퇴장 동작 확인 (채팅방 멤버 삭제)

hotfix/chatroom-exit-unsubscribe-1: 기존에 DISCONNECT 했던 채팅방을 UNSUBSCRIBE로 퇴장을 구현함

---

src/main/java/com/dife/api/config/WebSockConfig.java
src/main/java/com/dife/api/config/WebSocketInterceptor.java
src/main/java/com/dife/api/exception/StompExceptionHandler.java
src/main/java/com/dife/api/model/Member.java
src/main/java/com/dife/api/service/ChatService.java
src/main/java/com/dife/api/service/ChatroomService.java

- 현재 웹소켓의 연결이 끊길 때 원인이 잘 나오지 않는 문제가 있다.
- 에러 발생 시, 원인을 전달하기 위해 StompSubProtocolHandler를 직접
작성한다.
- Interceptor에서 에러 체킹을 추가한다.
- 에러 발생 시, 원인을 전달하기 위해 StompSubProtocolHandler를 직접
- 빠른 구현을 위해 링크 참고해서 일부만 수정함: https://velog.io/@jkijki12/%EC%B1%84%ED%8C%85-STOMP-JWT
- WebsocketInterceptor에서, JWT가 필요한 Command와 그렇지 않은
Command를 구분해서 알맞게 상황처리를 해준다.
- CONNECT, SEND, MESSAGE, SUBSCRIBE는 JWT 필요
- CONNECT의 경우에는 초기 auth 설정해줌
- SUBSCRIBE의 경우에 destination 체킹 진행
- SUBSCRIBE 때, 구독 권한이 있는지 확인한다.
- chatroom.getMembers().contains(member) 이 부분에서 Member 인스턴스가
달라도, id로 멤버가 포함되어있는지 체킹이 필요하기 때문에, equals와
hashcode 함께 override (Convention 따라, o 변수 사용)

 fix(error): 웹소켓 에러 시에 이유 함께 보낼 수 있도록 처리

---

src/main/java/com/dife/api/handler/DisconnectHandler.java
src/main/java/com/dife/api/service/ChatService.java

- 기존에 채팅방 퇴장하면 DISCONNECT 했던 것을 UNSUBSCRIBE로 수정
-  messagingTemplate 이용해 UNSUBSCRIBE 메시지 직접 서버에서 전송
- 앞선 채팅방 인증 코드 merge 후에 merge 예정

refactor/chat-exit-auth-1: 개선된 채팅 인증/인가 적용한 채팅방 퇴장 수정
